extends:
  - react-app
  - ../.eslintrc.yml
parserOptions:
  project: ./tsconfig.app.json
overrides:
  - files:
      - vite.config.ts
    parserOptions:
      project: ./tsconfig.node.json
rules:
  '@typescript-eslint/no-restricted-imports':
    - error
    - patterns:
        - group:
            - '@ideanick/server/**'
            - '!@ideanick/server/**/'
            - '!@ideanick/server/**/input'
          allowTypeImports: true
          message: 'Only types and input schemas are allowed to be imported from backend workspace'
